// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package shopdb

import (
	"time"

	dbtypes "github.com/mathis-sperlich/gearbox/example/dbtypes"
)

type Customer struct {
	ID                 string `db:"id"`
	Name               string `db:"name"`
	LifetimeSpendCents int64  `db:"lifetime_spend_cents"`
}

type Order struct {
	ID           string              `db:"id"`
	CustomerID   string              `db:"customer_id"`
	ProductID    string              `db:"product_id"`
	Quantity     int32               `db:"quantity"`
	Status       dbtypes.OrderStatus `db:"status"`
	TotalCents   int64               `db:"total_cents"`
	Currency     string              `db:"currency"`
	PaymentRef   string              `db:"payment_ref"`
	TrackingCode string              `db:"tracking_code"`
	CancelReason string              `db:"cancel_reason"`
	PlacedAt     time.Time           `db:"placed_at"`
	PaidAt       *time.Time          `db:"paid_at"`
	ShippedAt    *time.Time          `db:"shipped_at"`
	UpdatedAt    time.Time           `db:"updated_at"`
}

type OrderEvent struct {
	ID      string    `db:"id"`
	OrderID string    `db:"order_id"`
	Kind    string    `db:"kind"`
	Detail  string    `db:"detail"`
	At      time.Time `db:"at"`
}

type Product struct {
	ID         string `db:"id"`
	Name       string `db:"name"`
	Stock      int32  `db:"stock"`
	PriceCents int64  `db:"price_cents"`
}
