// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package shopdb

import (
	"context"
	"time"
)

const listExpiredPlacedOrders = `-- name: ListExpiredPlacedOrders :many

select id from orders
where status = 'placed' and placed_at < $1::timestamptz
order by id
for update skip locked
`

// The whole shop runs on gearbox's generic CRUD helpers (Get/Insert/Update/…)
// over the sqlc-generated structs — so there are no per-operation queries here.
// This one stays as sqlc: a FOR UPDATE SKIP LOCKED drain has no CRUD equivalent,
// and it shows the escape hatch — drop to sqlc whenever a query earns it.
func (q *Queries) ListExpiredPlacedOrders(ctx context.Context, dollar_1 time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredPlacedOrders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
